export default  {
    TOGGLE_MODAL:"TOGGLE_MODAL",
    GET_AD_CHOICES:"GET_AD_CHOICES",
    ADD_TO_CART:"ADD_TO_CART",
    UPDATE_CART_ITEM:"UPDATE_CART_ITEM",
    TOGGLE_CART:"TOGGLE_CART",
    GET_INPUT:"GET_INPUT",
    MAKE_PAYMENT:"MAKE_PAYMENT"
};
